# Principal Component Analysis

In [3]:
import numpy as np
import os

# to make this notebook's output stable across runs
np.random.seed(42)

# To plot pretty figures
%matplotlib inline
import matplotlib
import matplotlib.pyplot as plt
plt.rcParams['axes.labelsize'] = 14
plt.rcParams['xtick.labelsize'] = 12
plt.rcParams['ytick.labelsize'] = 12

from sklearn.decomposition import PCA

In [8]:
m = 60
w1, w2 = 0.1, 0.3
noise = 0.1

angles = np.random.rand(m) * 3 * np.pi / 2 - 0.5
X = np.empty((m, 3))
X[:, 0] = np.cos(angles) + np.sin(angles)/2 + noise * np.random.randn(m) / 2
X[:, 1] = np.sin(angles) * 0.7 + noise * np.random.randn(m) / 2
X[:, 2] = X[:, 0] * w1 + X[:, 1] * w2 + noise * np.random.randn(m)

# Running PCS on sklearn is very easy
pca = PCA(n_components = 2)
X2D = pca.fit_transform(X)

# 2D projection
X2D

array([[ 0.95077309, -0.2308092 ],
       [-0.73140197,  0.17978878],
       [-0.86075863,  0.12277505],
       [-0.54385048,  0.46489064],
       [-0.75918085,  0.08235719],
       [-0.8407742 , -0.14914684],
       [-0.80614298,  0.05262986],
       [-0.5699995 ,  0.46299731],
       [-0.63838938,  0.46043219],
       [-0.12680859, -0.37222046],
       [-0.81854718,  0.16379344],
       [-0.56011143, -0.33661634],
       [ 0.04896666, -0.37941349],
       [ 0.99067679, -0.26037304],
       [-0.40677968,  0.55978873],
       [ 1.45424458,  0.19837986],
       [ 0.75250957, -0.30023799],
       [-0.57755635,  0.61374639],
       [ 1.46715923,  0.38406555],
       [ 1.53831002,  0.50261502],
       [-0.48078354,  0.62266439],
       [-0.83036756, -0.15308684],
       [ 1.50122318,  0.18332701],
       [ 1.20815351,  0.00970269],
       [-0.78449853,  0.10474145],
       [-0.86133263, -0.0158546 ],
       [-0.52899914, -0.34031688],
       [ 0.03173058, -0.44387507],
       [ 0.78758945,

In [10]:
# We can recover the 3D projection
X3D_inv = pca.inverse_transform(X2D)

# There will be some loss of information
np.allclose(X3D_inv, X)

False

In [11]:
# We can calculate the error of returning to a 3D representation
np.mean(np.sum(np.square(X3D_inv - X), axis=1))

0.011314282069198146

In [12]:
# Looking at the principal components
pca.components_

array([[-0.98196733, -0.13489777, -0.13244907],
       [ 0.16476254, -0.95420546, -0.2496903 ]])

In [18]:
# Looking at the explanation capabilities of each dimension
pca.explained_variance_ratio_
# First dimension explains 84.2% of the variance, second explains 14.6%
# Note the third dimension explains 100%-(84%+14%) = 2%

array([0.84212839, 0.14390061])

In [19]:
# We can look at variance lost due to 2D projection
1 - pca.explained_variance_ratio_.sum()

0.01397100070575763

### Choosing the Right Number of Dimensions

Usually we want to reduce the number of dimensions up to a certain variance (unless we want to visualize the data, in which we are stuck to either 2 or 3 dimensions)

In [23]:
pca = PCA()
pca.fit(X)

# Summing variances
cumsum = np.cumsum(pca.explained_variance_ratio_)
d = np.argmax(cumsum >= 0.95) + 1

# Now we woulf only need to re-run with n_components=d

In [25]:
# An alternative is to directly specify the variance threshold
pca = PCA(n_components=0.95)
X_reduced = pca.fit_transform(X)